environment:
  matrix:
  # Releases
#  - JULIAVERSION: "stable/win32"
  - JULIAVERSION: "stable/win64"
  # Nightlies
#  - JULIAVERSION: "download/win32"
#  - JULIAVERSION: "download/win64"

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
  #- IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.clone(pwd(), \"Nemo\"); Pkg.build(\"Nemo\");"

test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"Nemo\")"
