title = "metadata for Oscar CI run"

[env]
os = [ ["Linux", "RPTU", "normal-memory"] ]
# os = [ "ubuntu-latest" ]
# julia-version = [ "~1.6.0-0" ]
# branches = [ "<matching>", "release" ]

[pkgs]
  [pkgs.Oscar]
  test = true

  [pkgs.Nemo]
  test = false

  [pkgs.Singular]
  test = false

  [pkgs.Hecke]
  test = false

[include]
  [include.justoscarmaster]
  Oscar = "master"
  Singular = "release"
  Hecke = "release"
  Nemo = "release"
  julia-version = "1.10"
  os = ["Linux", "RPTU", "normal-memory"]
